"""Initial schema: all models

Revision ID: 30b840d15fd1
Revises:
Create Date: 2026-06-08 15:36:38.355803

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "30b840d15fd1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
